#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CONFIG_FILE="${PROJECT_ROOT}/platform/rtps/config_local.h"
IP_ADDR="${1:-}"

if [ -z "${IP_ADDR}" ]; then
  IP_ADDR="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i=1; i<=NF; i++) if ($i=="src") {print $(i+1); exit}}')"
fi
if [ -z "${IP_ADDR}" ]; then
  IP_ADDR="$(hostname -I | awk '{print $1}')"
fi

if [[ ! "${IP_ADDR}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
  echo "[qos-ip] invalid IPv4 address: ${IP_ADDR}" >&2
  exit 1
fi

IFS=. read -r a b c d <<<"${IP_ADDR}"
for octet in "$a" "$b" "$c" "$d"; do
  if [ "${octet}" -lt 0 ] || [ "${octet}" -gt 255 ]; then
    echo "[qos-ip] invalid IPv4 octet in ${IP_ADDR}" >&2
    exit 1
  fi
done

OLD_LINE=""
if [ -f "${CONFIG_FILE}" ]; then
  OLD_LINE="$(grep -E 'REMOTE_PARTICIPANT_IP\{[0-9, ]+\}' "${CONFIG_FILE}" || true)"
fi
NEW_EXPR="REMOTE_PARTICIPANT_IP{${a}, ${b}, ${c}, ${d}}"

cat >"${CONFIG_FILE}" <<EOF
#pragma once

// Local ROS2/WSL participant IP generated by scripts/demo/qos_set_remote_ip.sh.
// This file is intentionally ignored by git.
const std::array<uint8_t, 4> ${NEW_EXPR};
EOF

echo "[qos-ip] WSL/ROS2 IPv4: ${IP_ADDR}"
echo "[qos-ip] old: ${OLD_LINE}"
echo "[qos-ip] new: const std::array<uint8_t, 4> ${NEW_EXPR};"
